package unicam.hackhub.domain.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Represents a call proposed by a mentor in response to a support request.
 * Booking is delegated to the external Calendar system.
 *
 * Relationships (from Analysis_Diagram):
 * - generated by 1 SupportRequest
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "mentor_call")
public class MentorCall {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String link;

    @Column(nullable = false)
    private LocalDate date;

    @Column(nullable = false)
    private int duration;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private CallStatus status;

    /** Support request that generated this call */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "support_request_id", nullable = false)
    private SupportRequest supportRequest;

    public MentorCall(String link, LocalDate date, int duration, SupportRequest supportRequest) {
        this.link = link;
        this.date = date;
        this.duration = duration;
        this.supportRequest = supportRequest;
        this.status = CallStatus.SCHEDULED;
    }

    public enum CallStatus {
        SCHEDULED,  // call booked via Calendar
        COMPLETED,  // call took place
        CANCELLED   // call was cancelled
    }
}